#!/usr/bin/env python3
# RELEASE: nodusrf/nodus-edge setup.py
"""
NodusNet Edge Node Setup Wizard

Interactive setup for edge nodes. Collects user inputs,
resolves geographic data, fetches local repeaters from RepeaterBook,
and generates .env + repeaters.json for the edge node.

Usage:
    python setup-edge.py                          # Interactive mode
    python setup-edge.py --zip 85001 --non-interactive  # Scripted mode
    python setup-edge.py --dry-run                # Preview without writing

Requires only Python 3.8+ stdlib (no pip install needed).
"""

import argparse
import hashlib
import json
import math
import os
import re
import socket
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ZIPPOPOTAM_API = "https://api.zippopotam.us/us/{zip}"
USER_AGENT = "NodusNet-Setup/1.0 (+https://nodusrf.com; nodusrf@proton.me)"

# Path to bundled zip->metro CBSA mapping (generated by generate-zip-metro.py)
# Can be overridden via NODUSNET_ZIP_METRO_PATH env var (used by install-edge.sh)
ZIP_METRO_PATH = Path(
    os.environ.get("NODUSNET_ZIP_METRO_PATH", "")
    or str(Path(__file__).resolve().parent.parent / "recept/src/recept/data/zip_metro.json")
)

# Offline 2m repeater bundle (fallback when RepeaterBook API is unavailable)
REPEATERS_2M_PATH = Path(
    os.environ.get("NODUSNET_REPEATERS_2M_PATH", "")
    or str(Path(__file__).resolve().parent.parent / "recept/src/recept/data/repeaters_2m_us.json")
)

NATIONAL_SIMPLEX_2M_HZ = 146_520_000
DEFAULT_RADIUS_MILES = 50
CORE_FREQ_COUNT = 10

# RTL-SDR usable bandwidth (after FFT rolloff, ~90% of sample rate)
RTLSDR_USABLE_BW_HZ = 2_160_000  # ~2.16 MHz usable from 2.4 Msps

# Callsign regex: 1-2 letters, 1 digit, 1-3 letters (US format)
CALLSIGN_RE = re.compile(r"^[A-Za-z]{1,2}[0-9][A-Za-z]{1,3}$")
# Broader international format
CALLSIGN_BROAD_RE = re.compile(r"^[A-Za-z0-9]{3,7}$")

ZIP_RE = re.compile(r"^\d{5}$")

# Colors
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
BOLD = "\033[1m"
NC = "\033[0m"

STATE_ABBREV_TO_NAME = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
    "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine",
    "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska",
    "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico",
    "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
    "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island",
    "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas",
    "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def info(msg: str) -> None:
    print(f"  {GREEN}[INFO]{NC} {msg}")


def warn(msg: str) -> None:
    print(f"  {YELLOW}[WARN]{NC} {msg}")


def error(msg: str) -> None:
    print(f"  {RED}[ERROR]{NC} {msg}")


def prompt(question: str, default: str = "", validator=None) -> str:
    """Prompt user for input with optional default and validation."""
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            answer = input(f"  {question}{suffix}: ").strip()
        except EOFError:
            answer = ""
        if not answer and default:
            answer = default
        if validator:
            err = validator(answer)
            if err:
                error(err)
                continue
        return answer


def prompt_yn(question: str, default_yes: bool = True) -> bool:
    """Prompt for yes/no answer."""
    hint = "Y/n" if default_yes else "y/N"
    while True:
        try:
            answer = input(f"  {question} [{hint}]: ").strip().lower()
        except EOFError:
            answer = ""
        if not answer:
            return default_yes
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        error("Please enter y or n.")


def load_zip_metro() -> dict:
    """Load the bundled zip->metro CBSA mapping if available."""
    if not ZIP_METRO_PATH.exists():
        return {}
    try:
        with open(ZIP_METRO_PATH) as f:
            data = json.load(f)
        return data.get("zips", {})
    except (json.JSONDecodeError, KeyError):
        return {}


def lookup_metro(zip_code: str, city: str, zip_metro: dict) -> str:
    """Resolve metro slug from zip code using CBSA mapping, with city fallback."""
    # Try CBSA mapping first (handles Elkhorn->omaha, Scottsdale->phoenix)
    if zip_code in zip_metro:
        return zip_metro[zip_code]
    # Fallback: slugify the city name from the zip API
    return slugify_city(city)


def slugify_city(city: str) -> str:
    """Normalize city name to a slug (fallback when CBSA mapping misses)."""
    slug = city.lower()
    slug = re.sub(r"[^a-z0-9]", "", slug)
    return slug[:20]


def haversine_distance(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Distance between two points in miles."""
    R = 3959  # Earth radius in miles
    lat1_r, lat2_r = math.radians(lat1), math.radians(lat2)
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_r) * math.cos(lat2_r) * math.sin(dlon / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ---------------------------------------------------------------------------
# Step 1: Server Connection
# ---------------------------------------------------------------------------

def ask_server_connection(args) -> dict:
    """Ask whether to connect to NodusNet server."""
    if args.non_interactive:
        server = args.server or ""
        token = args.api_key or ""
        return {
            "synapse_endpoint": server if server else "",
            "synapse_auth_token": token,
        }

    print()
    print(f"  {BOLD}Step 1: Server Connection{NC}")
    print(f"  {'─' * 50}")
    print()

    connected = prompt_yn("Are you connecting to the NodusNet server?")

    if not connected:
        info("Standalone mode: segments will be saved locally only.")
        return {"synapse_endpoint": "", "synapse_auth_token": ""}

    server = prompt(
        "NodusNet server endpoint",
        default="https://nodusrf.com",
    )

    # Normalize: strip trailing slash
    server = server.rstrip("/")

    # Test connectivity
    try:
        req = Request(f"{server}/health")
        req.add_header("User-Agent", USER_AGENT)
        urlopen(req, timeout=5)
        info(f"Connected to {server}")
    except Exception:
        warn(f"Could not reach {server} — you can fix the endpoint in .env later.")

    token = ""
    has_key = prompt_yn("Do you have an API key?", default_yes=False)
    if has_key:
        token = prompt("API key")

    return {
        "synapse_endpoint": server,
        "synapse_auth_token": token,
    }


# ---------------------------------------------------------------------------
# Step 1: Location
# ---------------------------------------------------------------------------

def resolve_zip(zip_code: str) -> dict:
    """Resolve zip code via zippopotam.us API."""
    url = ZIPPOPOTAM_API.format(zip=zip_code)
    req = Request(url)
    req.add_header("User-Agent", USER_AGENT)

    with urlopen(req, timeout=10) as response:
        data = json.loads(response.read().decode("utf-8"))

    place = data["places"][0]
    return {
        "lat": float(place["latitude"]),
        "lon": float(place["longitude"]),
        "city": place["place name"],
        "state": place["state"],
        "state_abbrev": place["state abbreviation"],
    }


def ask_manual_location() -> dict:
    """Fall back to manual location entry."""
    print()
    warn("Enter your location manually:")

    def validate_float(v):
        try:
            float(v)
            return None
        except ValueError:
            return "Must be a number."

    def validate_state(v):
        if v.upper() not in STATE_ABBREV_TO_NAME:
            return "Unknown state abbreviation."
        return None

    lat = float(prompt("Latitude", validator=validate_float))
    lon = float(prompt("Longitude", validator=validate_float))
    city = prompt("City")
    state_abbrev = prompt("State abbreviation (e.g. AZ)", validator=validate_state).upper()
    state = STATE_ABBREV_TO_NAME[state_abbrev]

    return {
        "lat": lat,
        "lon": lon,
        "city": city,
        "state": state,
        "state_abbrev": state_abbrev,
    }


def ask_location(args, zip_metro: dict) -> dict:
    """Ask for zip code, resolve to location + metro."""
    if args.non_interactive:
        # Non-interactive: use CLI args
        if args.lat and args.lon and args.city and args.state:
            state_name = STATE_ABBREV_TO_NAME.get(args.state.upper(), args.state)
            loc = {
                "lat": args.lat, "lon": args.lon,
                "city": args.city, "state": state_name,
                "state_abbrev": args.state.upper(),
            }
            zip_code = args.zip or ""
        elif args.zip:
            loc = resolve_zip(args.zip)
            zip_code = args.zip
        else:
            error("Non-interactive mode requires --zip or --lat/--lon/--city/--state")
            sys.exit(1)

        metro = args.metro or lookup_metro(zip_code, loc["city"], zip_metro)
        loc["metro"] = metro
        return loc

    print()
    print(f"  {BOLD}Step 1: Location{NC}")
    print(f"  {'─' * 50}")
    print()

    zip_code = ""
    while True:
        zip_code = prompt("What is your zip code?")

        if not ZIP_RE.match(zip_code):
            error("Zip code must be exactly 5 digits.")
            continue

        try:
            loc = resolve_zip(zip_code)
            break
        except HTTPError as e:
            if e.code == 404:
                error(f"Zip code {zip_code} not found.")
            else:
                error(f"API error: {e.code}")
                if prompt_yn("Enter location manually?"):
                    loc = ask_manual_location()
                    zip_code = ""
                    break
        except (URLError, Exception) as e:
            warn(f"Could not reach zip code API: {e}")
            if prompt_yn("Enter location manually?"):
                loc = ask_manual_location()
                zip_code = ""
                break

    info(f"Location: {loc['city']}, {loc.get('state_abbrev', '')} ({loc['lat']:.4f}, {loc['lon']:.4f})")
    print()

    # Resolve metro via CBSA mapping, fall back to city name
    default_metro = lookup_metro(zip_code, loc["city"], zip_metro)
    cbsa_source = " (CBSA)" if zip_code in zip_metro else ""
    print(f"  Your metro area will be: {BOLD}{default_metro}{NC}{cbsa_source} ({loc['city']}, {loc.get('state_abbrev', '')})")
    if not prompt_yn("Is this correct?"):
        error("Re-run setup with a different zip code, or edit .env after setup.")
        sys.exit(1)
    loc["metro"] = default_metro

    info(f"Metro: {loc['metro']}")
    return loc


# ---------------------------------------------------------------------------
# Step 2: Callsign
# ---------------------------------------------------------------------------

def ask_callsign(args) -> str:
    """Ask for operator callsign (optional)."""
    if args.non_interactive:
        return (args.callsign or "").upper()

    print()
    print(f"  {BOLD}Step 2: Callsign{NC}")
    print(f"  {'─' * 50}")
    print()

    callsign = prompt("What is your callsign? (optional, Enter to skip)")

    if not callsign:
        info("No callsign — node will be anonymous.")
        return ""

    callsign = callsign.upper()

    if CALLSIGN_RE.match(callsign):
        info(f"Callsign: {callsign}")
        return callsign

    if CALLSIGN_BROAD_RE.match(callsign):
        warn(f"{callsign} doesn't match standard US callsign format.")
        if prompt_yn("Use it anyway?"):
            return callsign
        return ""

    warn(f"{callsign} doesn't look like a valid callsign.")
    if prompt_yn("Use it anyway?", default_yes=False):
        return callsign
    return ""


# ---------------------------------------------------------------------------
# Node ID
# ---------------------------------------------------------------------------

def derive_node_id(callsign: str, metro: str) -> str:
    """Derive node ID from callsign and metro."""
    if callsign:
        return f"{callsign.lower()}-fm-{metro}"
    else:
        seed = f"{socket.gethostname()}-{time.time()}"
        h = hashlib.sha256(seed.encode()).hexdigest()[:4]
        return f"anon-fm-{metro}-{h}"


# ---------------------------------------------------------------------------
# Step 3: Repeater Discovery
# ---------------------------------------------------------------------------

def load_offline_repeaters() -> list:
    """Load the bundled offline 2m repeater database."""
    path = REPEATERS_2M_PATH
    if not path.exists():
        return []
    try:
        with open(path) as f:
            data = json.load(f)
        return data.get("repeaters", [])
    except (json.JSONDecodeError, OSError):
        return []


def fetch_repeaters(lat: float, lon: float, state_name: str,
                    radius_miles: float = DEFAULT_RADIUS_MILES) -> tuple:
    """Find 2m repeaters near location from bundled offline data.

    Returns (repeaters_list, metadata_dict).
    """
    metadata = {
        "center_lat": lat,
        "center_lon": lon,
        "radius_miles": radius_miles,
        "fetched_at": datetime.now(timezone.utc).isoformat(),
        "source": "offline-bundle",
        "band": "2m",
    }

    print()
    info(f"Searching bundled repeater data for 2m repeaters within {radius_miles} miles...")

    all_repeaters = load_offline_repeaters()
    if not all_repeaters:
        warn("Offline repeater database not found.")
        warn(f"Looked in: {REPEATERS_2M_PATH}")
        metadata["total_repeaters"] = 0
        return [], metadata

    info(f"Loaded {len(all_repeaters)} US 2m repeaters from offline database.")

    # Filter by distance
    nearby = []
    for rptr in all_repeaters:
        try:
            rlat = float(rptr.get("Lat", 0))
            rlon = float(rptr.get("Long", 0))
            if rlat == 0 or rlon == 0:
                continue
            dist = haversine_distance(lat, lon, rlat, rlon)
            if dist <= radius_miles:
                rptr["_distance_miles"] = round(dist, 1)
                nearby.append(rptr)
        except (ValueError, TypeError):
            continue

    # Deduplicate by (Frequency, Callsign), sort by distance
    seen = set()
    unique = []
    for rptr in sorted(nearby, key=lambda x: x.get("_distance_miles", 9999)):
        key = (rptr.get("Frequency"), rptr.get("Callsign"))
        if key not in seen:
            seen.add(key)
            unique.append(rptr)

    metadata["total_repeaters"] = len(unique)
    info(f"Found {len(unique)} repeaters within {radius_miles} miles.")

    return unique, metadata


def split_frequencies(repeaters: list) -> tuple:
    """Split repeaters into core and candidate frequency lists.

    Returns (core_hz, candidate_hz).
    Core: national simplex + top 10 closest active repeaters.
    Candidate: remaining repeaters within radius.
    """
    core_hz = [NATIONAL_SIMPLEX_2M_HZ]

    # Filter to operational repeaters
    active = [r for r in repeaters
              if r.get("Operational Status", "").strip().lower() in ("on-air", "")]

    for rptr in active[:CORE_FREQ_COUNT]:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            if freq_hz not in core_hz:
                core_hz.append(freq_hz)
        except (ValueError, KeyError):
            continue

    core_set = set(core_hz)
    candidate_hz = []
    for rptr in active[CORE_FREQ_COUNT:]:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            if freq_hz not in core_set:
                candidate_hz.append(freq_hz)
        except (ValueError, KeyError):
            continue

    return core_hz, candidate_hz


def check_bandwidth(frequencies: list, repeaters: list) -> tuple:
    """Check if frequencies fit within RTL-SDR usable bandwidth.

    Returns (fits: bool, span_mhz: float, max_mhz: float, over_freqs: list).
    over_freqs is a list of (freq_hz, callsign, distance) for frequencies
    that would need to be dropped to fit.
    """
    if len(frequencies) < 2:
        return True, 0.0, RTLSDR_USABLE_BW_HZ / 1_000_000, []

    sorted_freqs = sorted(frequencies)
    span = sorted_freqs[-1] - sorted_freqs[0]
    max_bw = RTLSDR_USABLE_BW_HZ
    fits = span <= max_bw

    over_freqs = []
    if not fits:
        # Identify which edge frequencies would need to be dropped.
        # Try trimming from the high end first, then low end.
        center = (sorted_freqs[0] + sorted_freqs[-1]) // 2
        half_bw = max_bw // 2
        for freq_hz in sorted_freqs:
            if freq_hz < center - half_bw or freq_hz > center + half_bw:
                # Find repeater info
                callsign = ""
                distance = ""
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                            callsign = rptr.get("Callsign", "")
                            distance = rptr.get("_distance_miles", "?")
                            break
                    except (ValueError, KeyError):
                        continue
                over_freqs.append((freq_hz, callsign, distance))

    return fits, span / 1_000_000, max_bw / 1_000_000, over_freqs


def ask_repeaters(args, lat: float, lon: float, state_name: str) -> tuple:
    """Fetch repeaters and get user confirmation.

    Returns (core_hz, candidate_hz, repeaters, metadata).
    """
    radius = args.radius

    print()
    print(f"  {BOLD}Step 3: Repeater Discovery{NC}")
    print(f"  {'─' * 50}")

    # Band selection
    if not args.non_interactive:
        print()
        print(f"    [1] {BOLD}2 Meter{NC} (144-148 MHz)")
        print(f"    [2] {BOLD}70 Centimeter{NC} (420-450 MHz)")
        print(f"    [3] {BOLD}1.25 Meter{NC} (222-225 MHz)")
        print()
        band_choice = prompt("Which band will you be monitoring?", default="1")
    else:
        band_choice = "1"

    band_map = {"1": "2m", "2": "70cm", "3": "1.25m"}
    selected_band = band_map.get(band_choice, "2m")

    if selected_band != "2m":
        warn(f"Offline repeater data for {selected_band} is not yet available.")
        info("The national simplex frequency will be configured.")
        info("Add repeater frequencies manually in .env after setup.")
        # Return just simplex for the selected band
        simplex_map = {"70cm": 446_000_000, "1.25m": 223_500_000}
        simplex_hz = simplex_map.get(selected_band, NATIONAL_SIMPLEX_2M_HZ)
        metadata = {
            "center_lat": lat, "center_lon": lon,
            "radius_miles": radius,
            "fetched_at": datetime.now(timezone.utc).isoformat(),
            "source": "manual", "band": selected_band,
        }
        return [simplex_hz], [], [], metadata

    repeaters, metadata = fetch_repeaters(lat, lon, state_name, radius)
    core_hz, candidate_hz = split_frequencies(repeaters)

    print()
    info(f"Found {len(repeaters)} repeaters in the 2m band within {radius} miles.")
    print()

    if core_hz:
        print(f"  {BOLD}Core frequencies (always monitored):{NC}")
        for freq_hz in core_hz:
            freq_mhz = freq_hz / 1_000_000
            # Find matching repeater info
            label = ""
            if freq_hz == NATIONAL_SIMPLEX_2M_HZ:
                label = "National simplex"
            else:
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                            cs = rptr.get("Callsign", "")
                            dist = rptr.get("_distance_miles", "?")
                            city = rptr.get("Nearest City", "")
                            label = f"{cs}  ({dist} mi) {city}"
                            break
                    except (ValueError, KeyError):
                        continue
            print(f"    {freq_mhz:>10.3f} MHz  {label}")

    if candidate_hz:
        print()
        print(f"  {BOLD}Candidate frequencies (promoted when active): {len(candidate_hz)}{NC}")
        # Show first 5 candidates
        for freq_hz in candidate_hz[:5]:
            freq_mhz = freq_hz / 1_000_000
            for rptr in repeaters:
                try:
                    if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                        cs = rptr.get("Callsign", "")
                        dist = rptr.get("_distance_miles", "?")
                        city = rptr.get("Nearest City", "")
                        print(f"    {freq_mhz:>10.3f} MHz  {cs}  ({dist} mi) {city}")
                        break
                except (ValueError, KeyError):
                    continue
        if len(candidate_hz) > 5:
            print(f"    ... and {len(candidate_hz) - 5} more")

    if not repeaters:
        warn("No 2m repeaters found in your area.")
        info("146.520 MHz (national simplex) will be your only core frequency.")
        info("You can add frequencies manually in the .env file later.")

    # Bandwidth check: do all core frequencies fit in one RTL-SDR?
    fits, span_mhz, max_mhz, over_freqs = check_bandwidth(core_hz, repeaters)
    if not fits:
        print()
        warn(f"SDR bandwidth exceeded: your core frequencies span {span_mhz:.1f} MHz,")
        warn(f"but one RTL-SDR dongle can only cover ~{max_mhz:.1f} MHz at a time.")
        print()
        print(f"  An SDR captures a continuous {BOLD}slice of spectrum{NC} — it's not like a")
        print(f"  radio that hops between frequencies. All your frequencies must fit")
        print(f"  within that slice, or the edge ones won't be received.")
        print()
        if over_freqs:
            print(f"  {BOLD}Frequencies outside the usable window:{NC}")
            for freq_hz, callsign, distance in over_freqs:
                label = f"{callsign}  ({distance} mi)" if callsign else ""
                print(f"    {RED}{freq_hz / 1_000_000:>10.3f} MHz{NC}  {label}")
        print()
        print(f"  Options:")
        print(f"    1. {BOLD}Drop the out-of-range frequencies{NC} to fit within one dongle")
        print(f"    2. {BOLD}Add a second RTL-SDR dongle{NC} to cover additional spectrum")
        print(f"    3. {BOLD}Keep them anyway{NC} (edge frequencies may have degraded reception)")
        print()

        if not args.non_interactive:
            choice = prompt("Choose (1/2/3)", default="3")
            if choice == "1":
                drop_set = {f for f, _, _ in over_freqs}
                core_hz = [f for f in core_hz if f not in drop_set]
                info(f"Trimmed to {len(core_hz)} core frequencies within SDR bandwidth.")
            elif choice == "2":
                info("Multi-dongle: configure the second dongle in .env after setup.")
                info("Set RECEPT_FM_AIRBAND_CENTER_FREQ_HZ to optimize placement.")

    if not args.non_interactive:
        print()
        if not prompt_yn("Accept these frequencies? (you can always change them later)"):
            info("You can edit frequencies in the .env file after setup.")

    return core_hz, candidate_hz, repeaters, metadata


# ---------------------------------------------------------------------------
# Step 5b: Spectrum Coverage Assessment
# ---------------------------------------------------------------------------

def fetch_metro_coverage(server_url: str, metro: str, node_id: str, api_key: str = "") -> dict:
    """Fetch existing coverage data for a metro from the Gateway.

    Returns coverage map dict or empty dict on failure.
    """
    url = f"{server_url.rstrip('/')}/v1/edge/coverage/{metro}/suggestions?node_id={node_id}"
    headers = {"User-Agent": USER_AGENT}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except Exception:
        return {}


def fetch_metro_map(server_url: str, metro: str, api_key: str = "") -> dict:
    """Fetch the full coverage map for a metro."""
    url = f"{server_url.rstrip('/')}/v1/edge/coverage/{metro}"
    headers = {"User-Agent": USER_AGENT}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except Exception:
        return {}


def classify_band_simple(freq_hz: int) -> str:
    """Classify frequency into band name."""
    mhz = freq_hz / 1_000_000
    if 144 <= mhz <= 148:
        return "2m"
    if 222 <= mhz <= 225:
        return "1.25m"
    if 420 <= mhz <= 450:
        return "70cm"
    if 50 <= mhz <= 54:
        return "6m"
    if mhz < 30:
        return "hf"
    return "other"


def ask_spectrum_assessment(
    args,
    server_url: str,
    api_key: str,
    metro: str,
    node_id: str,
    core_hz: list,
    candidate_hz: list,
    repeaters: list,
) -> tuple:
    """Show metro coverage assessment and let operator adjust frequencies.

    Returns (core_hz, candidate_hz) potentially modified.
    """
    if not server_url or args.non_interactive:
        return core_hz, candidate_hz

    print()
    print(f"  {BOLD}Step 5b: Spectrum Coverage Assessment{NC}")
    print(f"  {'─' * 50}")
    print()

    # Fetch metro coverage map
    info("Checking existing spectrum coverage in your metro...")
    coverage_map = fetch_metro_map(server_url, metro, api_key)

    if not coverage_map or coverage_map.get("node_count", 0) == 0:
        info("No other nodes in your metro yet. You're the first!")
        info("Your frequency selections look great.")
        return core_hz, candidate_hz

    node_count = coverage_map.get("node_count", 0)
    band_summary = coverage_map.get("band_summary", {})
    freq_details = coverage_map.get("frequency_details", [])

    info(f"{node_count} other node{'s' if node_count != 1 else ''} already active in your metro.")
    print()

    # Show band coverage summary
    print(f"  {BOLD}Current metro band coverage:{NC}")
    for band_id, band_label in [("2m", "2 Meter"), ("70cm", "70cm"), ("1.25m", "1.25m (220)")]:
        bs = band_summary.get(band_id, {})
        nodes = bs.get("nodes", 0)
        freqs = bs.get("frequencies", 0)
        if nodes > 0:
            print(f"    {band_label:12s}  {nodes} node{'s' if nodes != 1 else ''}, {freqs} frequencies")
        else:
            print(f"    {band_label:12s}  {YELLOW}no coverage{NC}")
    print()

    # Check for over-covered frequencies in our proposed list
    my_freq_set = set(core_hz + candidate_hz)
    over_covered = []
    uncovered_by_us = []

    for fd in freq_details:
        fhz = fd["frequency_hz"]
        nc = fd["node_count"]
        if fhz in my_freq_set and nc >= 3:
            over_covered.append((fhz, nc))

    if over_covered:
        print(f"  {YELLOW}{BOLD}Overlap detected:{NC}")
        for fhz, nc in over_covered:
            label = ""
            for rptr in repeaters:
                try:
                    if int(float(rptr["Frequency"]) * 1_000_000) == fhz:
                        label = rptr.get("Callsign", "")
                        break
                except (ValueError, KeyError):
                    continue
            print(f"    {fhz / 1_000_000:>10.3f} MHz  already covered by {nc} nodes  {label}")
        print()
        print(f"  These frequencies have strong coverage already.")
        print(f"  Consider swapping some for uncovered repeaters to maximize")
        print(f"  your metro's overall spectrum coverage.")
        print()

    # Find repeaters in our list that nobody else covers (good!)
    unique_freqs = []
    for fhz in core_hz:
        covered_by_others = any(fd["frequency_hz"] == fhz for fd in freq_details)
        if not covered_by_others:
            unique_freqs.append(fhz)

    if unique_freqs:
        print(f"  {GREEN}{BOLD}Unique coverage you'd add:{NC}")
        for fhz in unique_freqs[:5]:
            label = ""
            if fhz == NATIONAL_SIMPLEX_2M_HZ:
                label = "National simplex"
            else:
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == fhz:
                            label = rptr.get("Callsign", "")
                            break
                    except (ValueError, KeyError):
                        continue
            print(f"    {fhz / 1_000_000:>10.3f} MHz  {label}")
        if len(unique_freqs) > 5:
            print(f"    ... and {len(unique_freqs) - 5} more")
        print()

    # Ask user what to do
    print(f"  Options:")
    print(f"    1. {BOLD}Accept proposed frequencies{NC} (recommended)")
    print(f"    2. {BOLD}Pick your own{NC} from the full repeater list")
    print()

    choice = prompt("Choose (1/2)", default="1")

    if choice == "2":
        core_hz, candidate_hz = interactive_frequency_picker(
            repeaters, core_hz, candidate_hz, freq_details,
        )

    return core_hz, candidate_hz


def interactive_frequency_picker(
    repeaters: list,
    current_core: list,
    current_candidates: list,
    metro_coverage: list,
) -> tuple:
    """Let the operator pick frequencies interactively.

    Returns (core_hz, candidate_hz).
    """
    # Build a map of metro coverage for display
    coverage_count = {}
    for fd in metro_coverage:
        coverage_count[fd["frequency_hz"]] = fd["node_count"]

    print()
    print(f"  {BOLD}Available repeaters (sorted by distance):{NC}")
    print()
    print(f"  {'#':>3s}  {'Freq MHz':>10s}  {'Callsign':8s}  {'Dist':>5s}  {'Other':>5s}  {'Status'}")
    print(f"  {'─' * 55}")

    # Build selectable list
    selectable = [{"frequency_hz": NATIONAL_SIMPLEX_2M_HZ, "label": "National simplex", "distance": 0}]

    for rptr in repeaters:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            selectable.append({
                "frequency_hz": freq_hz,
                "label": rptr.get("Callsign", ""),
                "distance": rptr.get("_distance_miles", "?"),
                "city": rptr.get("Nearest City", ""),
            })
        except (ValueError, KeyError):
            continue

    for i, item in enumerate(selectable[:30], 1):
        fhz = item["frequency_hz"]
        freq_mhz = fhz / 1_000_000
        label = item.get("label", "")
        dist = item.get("distance", "")
        others = coverage_count.get(fhz, 0)
        in_core = "*" if fhz in current_core else " "
        others_str = f"{others}" if others > 0 else "-"
        print(f"  {i:>3d}  {freq_mhz:>10.3f}  {label:8s}  {str(dist):>5s}  {others_str:>5s}  {in_core}")

    if len(selectable) > 30:
        print(f"  ... {len(selectable) - 30} more available")

    print()
    print(f"  * = currently selected as core")
    print(f"  'Other' column shows how many other metro nodes cover that frequency")
    print()

    selection = prompt(
        "Enter frequency numbers to use as core (comma-separated, e.g. 1,3,5,7)",
        default=",".join(str(i) for i in range(1, min(11, len(selectable) + 1))),
    )

    try:
        indices = [int(x.strip()) - 1 for x in selection.split(",") if x.strip()]
        new_core = []
        for idx in indices:
            if 0 <= idx < len(selectable):
                fhz = selectable[idx]["frequency_hz"]
                if fhz not in new_core:
                    new_core.append(fhz)
        if new_core:
            # Remaining become candidates
            core_set = set(new_core)
            new_candidates = [
                item["frequency_hz"]
                for item in selectable
                if item["frequency_hz"] not in core_set
            ]
            info(f"Selected {len(new_core)} core frequencies, {len(new_candidates)} candidates.")
            return new_core, new_candidates
    except ValueError:
        warn("Invalid selection, keeping original frequencies.")

    return current_core, current_candidates


# ---------------------------------------------------------------------------
# Step 4: RTL-SDR Device Selection
# ---------------------------------------------------------------------------

def detect_rtlsdr_devices() -> list:
    """Detect RTL-SDR USB devices via lsusb."""
    import subprocess
    devices = []
    try:
        result = subprocess.run(
            ["lsusb"], capture_output=True, text=True, timeout=5,
        )
        for line in result.stdout.splitlines():
            # RTL2832U vendor:product IDs
            if "0bda:2838" in line or "0bda:2832" in line:
                devices.append(line.strip())
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return devices


def ask_sdr_device(args) -> dict:
    """Detect and select RTL-SDR device."""
    if args.non_interactive:
        return {
            "device_index": args.sdr_device if args.sdr_device is not None else 0,
            "gain": args.sdr_gain if args.sdr_gain is not None else 40,
        }

    print()
    print(f"  {BOLD}Step 4: RTL-SDR Device{NC}")
    print(f"  {'─' * 50}")
    print()

    devices = detect_rtlsdr_devices()

    if not devices:
        warn("No RTL-SDR devices detected via USB.")
        info("Make sure your dongle is plugged in before starting the containers.")
        info("Using default: device index 0, gain 40")
        return {"device_index": 0, "gain": 40}

    if len(devices) == 1:
        info(f"Found 1 RTL-SDR: {devices[0]}")
        device_index = 0
        gain = 40
    else:
        info(f"Found {len(devices)} RTL-SDR devices:")
        for i, dev in enumerate(devices):
            print(f"    [{i}] {dev}")
        print()
        idx = prompt(f"Which device to use for FM scanning? (0-{len(devices)-1})", default="0")
        try:
            device_index = int(idx)
            if device_index < 0 or device_index >= len(devices):
                device_index = 0
                warn(f"Invalid index, using 0")
        except ValueError:
            device_index = 0

        gain = prompt("RTL-SDR gain (0-49, or 'auto')", default="40")

    return {
        "device_index": device_index,
        "gain": gain,
    }


# ---------------------------------------------------------------------------
# Step 5: RF Environment (Squelch)
# ---------------------------------------------------------------------------

RF_PRESETS = {
    "1": ("Urban / Noisy", "Near repeater sites, lots of RF", 40, 10.0),
    "2": ("Suburban / Moderate", "Default, good balance", 30, 6.0),
    "3": ("Rural / Quiet", "Weak signals, low noise floor", 20, 4.0),
}


def scan_noise_floor(device_index: int = 0, gain: str = "40") -> dict | None:
    """Scan 2m band with rtl_power to measure noise floor.

    Runs a quick sweep of 144-148 MHz and computes the 25th-percentile
    power level as the noise floor estimate.  Maps the result to
    recommended squelch / SNR settings.

    Returns dict with noise_floor_db, squelch_threshold,
    airband_squelch_snr_db, and label — or None on failure.
    """
    import shutil
    import subprocess
    import tempfile

    if not shutil.which("rtl_power"):
        return None

    fd, csv_path = tempfile.mkstemp(suffix=".csv")
    os.close(fd)

    try:
        cmd = [
            "rtl_power",
            "-d", str(device_index),
            "-f", "144M:148M:25k",  # 2m band, 25 kHz bins
            "-i", "2",               # 2s integration per window
            "-1",                     # single sweep then exit
        ]
        if gain and str(gain).lower() != "auto":
            cmd.extend(["-g", str(gain)])
        cmd.append(csv_path)

        subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        # Parse CSV: date, time, Hz_low, Hz_high, Hz_step, samples, dB, dB, ...
        powers = []
        with open(csv_path) as f:
            for line in f:
                parts = line.strip().split(",")
                if len(parts) > 6:
                    for val in parts[6:]:
                        try:
                            powers.append(float(val.strip()))
                        except ValueError:
                            pass

        if not powers:
            return None

        return classify_noise_floor(powers)
    except (subprocess.TimeoutExpired, OSError):
        return None
    finally:
        try:
            os.unlink(csv_path)
        except OSError:
            pass


def classify_noise_floor(powers: list) -> dict:
    """Map a list of power readings (dB) to squelch recommendations.

    Uses the 25th percentile as the noise floor estimate to avoid
    active signals skewing the result upward.
    """
    powers_sorted = sorted(powers)
    idx_25 = max(0, len(powers_sorted) // 4)
    noise_floor = powers_sorted[idx_25]

    if noise_floor > -45:
        sq, snr, label = 45, 12.0, "Very noisy"
    elif noise_floor > -55:
        sq, snr, label = 40, 10.0, "Urban / Noisy"
    elif noise_floor > -65:
        sq, snr, label = 30, 6.0, "Suburban / Moderate"
    else:
        sq, snr, label = 20, 4.0, "Rural / Quiet"

    return {
        "noise_floor_db": round(noise_floor, 1),
        "squelch_threshold": sq,
        "airband_squelch_snr_db": snr,
        "label": label,
    }


def ask_rf_environment(args, sdr_config: dict | None = None) -> dict:
    """Ask about RF environment to set squelch thresholds."""
    # CLI override takes priority
    if args.squelch is not None:
        return {
            "squelch_threshold": args.squelch,
            "airband_squelch_snr_db": 6.0,
        }

    if args.non_interactive:
        if getattr(args, "auto_squelch", False):
            device_index = (sdr_config or {}).get("device_index", 0)
            gain = (sdr_config or {}).get("gain", 40)
            result = scan_noise_floor(device_index, str(gain))
            if result:
                return {
                    "squelch_threshold": result["squelch_threshold"],
                    "airband_squelch_snr_db": result["airband_squelch_snr_db"],
                }
        return {"squelch_threshold": 30, "airband_squelch_snr_db": 6.0}

    print()
    print(f"  {BOLD}Step 5: RF Environment{NC}")
    print(f"  {'─' * 50}")
    print()
    print("  Squelch controls how much signal is needed to start recording.")
    print("  Too low = static-only recordings. Too high = missed weak signals.")
    print("  You can always adjust after setup. For now, give an estimate.")
    print()

    for key, (name, desc, sq, snr) in RF_PRESETS.items():
        print(f"    [{key}] {BOLD}{name}{NC}")
        print(f"        {desc} (squelch {sq}, SNR {snr} dB)")

    # Only show auto-detect if rtl_power is available
    import shutil
    has_rtl_power = shutil.which("rtl_power") is not None
    if has_rtl_power:
        print(f"    [A] {BOLD}Auto-detect{NC}")
        print(f"        Scan 2m band with RTL-SDR to measure noise floor (~10s)")
    print()

    default = "A" if has_rtl_power else "2"
    choice = prompt("Select RF environment", default=default)

    if choice.upper() == "A" and has_rtl_power:
        device_index = (sdr_config or {}).get("device_index", 0)
        gain = (sdr_config or {}).get("gain", 40)
        info("Scanning 2m band for noise floor — this takes about 10 seconds...")
        result = scan_noise_floor(device_index, str(gain))
        if result:
            info(f"Noise floor: {result['noise_floor_db']:.1f} dB → {result['label']}")
            info(f"Recommended squelch: {result['squelch_threshold']}, SNR: {result['airband_squelch_snr_db']} dB")
            print()
            if prompt_yn("Accept these settings?"):
                return {
                    "squelch_threshold": result["squelch_threshold"],
                    "airband_squelch_snr_db": result["airband_squelch_snr_db"],
                }
            warn("Falling back to manual selection.")
            choice = prompt("Select preset (1/2/3)", default="2")
        else:
            warn("Scan failed — RTL-SDR may be unavailable or busy.")
            warn("Falling back to manual selection.")
            choice = prompt("Select preset (1/2/3)", default="2")

    if choice not in RF_PRESETS:
        warn(f"Unknown choice '{choice}', using Suburban / Moderate.")
        choice = "2"

    _, _, squelch, snr = RF_PRESETS[choice]
    info(f"Squelch threshold: {squelch}, SNR: {snr} dB")
    print(f"  Tip: NodusEdge will recommend adjustments if squelch needs tuning.")

    return {"squelch_threshold": squelch, "airband_squelch_snr_db": snr}


# ---------------------------------------------------------------------------
# Step 6: Transcription (Whisper)
# ---------------------------------------------------------------------------

def is_raspberry_pi() -> bool:
    """Detect if running on a Raspberry Pi (too slow for local Whisper)."""
    import platform
    arch = platform.machine()
    if arch not in ("aarch64", "armv7l"):
        return False
    # Check /proc/cpuinfo for Raspberry Pi
    try:
        with open("/proc/cpuinfo") as f:
            cpuinfo = f.read()
        if "Raspberry Pi" in cpuinfo or "BCM2" in cpuinfo:
            return True
    except OSError:
        pass
    # Check device-tree model
    try:
        with open("/proc/device-tree/model") as f:
            model = f.read()
        if "Raspberry Pi" in model:
            return True
    except OSError:
        pass
    # Fallback: aarch64 with < 4GB RAM is likely a Pi or similar SBC
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    mem_kb = int(line.split()[1])
                    if mem_kb < 4_000_000:
                        return True
                    break
    except (OSError, ValueError):
        pass
    return False


def ask_whisper(args) -> str:
    """Ask for Whisper transcription endpoint."""
    pi_detected = is_raspberry_pi()

    if args.non_interactive:
        if pi_detected and args.whisper_url is None:
            return "https://nodusrf.com/v1"
        return args.whisper_url if args.whisper_url is not None else "http://whisper:8000"

    print()
    print(f"  {BOLD}Step 6: Transcription{NC}")
    print(f"  {'─' * 50}")
    print()

    if pi_detected:
        url = args.whisper_url or "https://nodusrf.com/v1"
        info("Raspberry Pi detected. Using NodusNet GPU pool for transcription.")
        info(f"Whisper endpoint: {url}")
    else:
        default_url = args.whisper_url if args.whisper_url is not None else "http://whisper:8000"

        url = prompt(
            "Whisper transcription endpoint",
            default=default_url,
        )

    if url:
        # Skip connectivity test for Docker internal DNS (container isn't running yet)
        if "://whisper:" in url:
            info(f"Using Docker internal DNS: {url}")
        else:
            # Test connectivity
            try:
                req = Request(url)
                req.add_header("User-Agent", USER_AGENT)
                urlopen(req, timeout=5)
                info(f"Whisper reachable at {url}")
            except Exception:
                warn(f"Could not reach {url} — you can fix this in .env later.")
    else:
        info("Transcription disabled. Set RECEPT_WHISPER_API_URL in .env to enable.")

    return url


# ---------------------------------------------------------------------------
# Step 7: Generate Output
# ---------------------------------------------------------------------------

ENV_TEMPLATE = """\
# NodusNet Edge Node Configuration
# Generated by setup-edge.py on {generated_at}
# Node: {node_id} | Metro: {metro}

# ---- Identity ----
RECEPT_MODE=fm
RECEPT_NODE_ID={node_id}
RECEPT_METRO={metro}
RECEPT_CALLSIGN={callsign}

# ---- Scanner ----
RECEPT_FM_SCANNER_BACKEND=airband
RECEPT_FM_CORE_FREQUENCIES={core_frequencies}
RECEPT_FM_CANDIDATE_FREQUENCIES={candidate_frequencies}
RECEPT_FM_RTL_DEVICE_INDEX={device_index}
RECEPT_FM_GAIN={gain}
# Squelch: raise if you get static-only recordings, lower if missing weak signals
RECEPT_FM_SQUELCH_THRESHOLD={squelch_threshold}
RECEPT_FM_AIRBAND_SQUELCH_SNR_DB={airband_squelch_snr_db}

# ---- Upstream ----
RECEPT_SYNAPSE_ENDPOINT={synapse_endpoint}
RECEPT_SYNAPSE_AUTH_TOKEN={synapse_auth_token}
RECEPT_DIAGNOSTICS_ENDPOINT={diagnostics_endpoint}
RECEPT_REM_ENDPOINT={rem_endpoint}

# ---- Transcription ----
RECEPT_WHISPER_API_URL={whisper_api_url}
RECEPT_WHISPER_AUTH_TOKEN={whisper_auth_token}
RECEPT_TRANSCRIPTION_ENABLED={transcription_enabled}
WHISPER_MODEL={whisper_model}

# ---- Logging ----
RECEPT_LOG_LEVEL=INFO
"""


def generate_env(output_dir: Path, config: dict) -> str:
    """Generate .env file content."""
    # Diagnostics endpoint defaults to same base as Synapse
    synapse_ep = config.get("synapse_endpoint", "")
    diagnostics_ep = config.get("diagnostics_endpoint", "") or synapse_ep

    return ENV_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        node_id=config["node_id"],
        metro=config["metro"],
        callsign=config.get("callsign", ""),
        core_frequencies=json.dumps(config["core_frequencies"]),
        candidate_frequencies=json.dumps(config["candidate_frequencies"]),
        synapse_endpoint=synapse_ep,
        synapse_auth_token=config.get("synapse_auth_token", ""),
        diagnostics_endpoint=diagnostics_ep,
        rem_endpoint=f"{synapse_ep}/v1" if synapse_ep else "",
        whisper_api_url=config.get("whisper_api_url", ""),
        whisper_auth_token=config.get("whisper_auth_token", ""),
        transcription_enabled="true" if config.get("whisper_api_url") else "false",
        whisper_model=config.get("whisper_model", "base"),
        device_index=config.get("device_index", 0),
        gain=config.get("gain", 40),
        squelch_threshold=config.get("squelch_threshold", 30),
        airband_squelch_snr_db=config.get("airband_squelch_snr_db", 6.0),
    )


def write_output(args, config: dict, repeaters: list, metadata: dict):
    """Write .env and repeaters.json to output directory."""
    output_dir = Path(args.output_dir)

    env_content = generate_env(output_dir, config)
    repeaters_data = json.dumps({"metadata": metadata, "repeaters": repeaters}, indent=2)

    if args.dry_run:
        print()
        print(f"  {BOLD}[DRY-RUN] .env contents:{NC}")
        for line in env_content.splitlines():
            print(f"    {line}")
        print()
        print(f"  {BOLD}[DRY-RUN] repeaters.json:{NC} {len(repeaters)} repeaters")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    env_path = output_dir / ".env"
    env_path.write_text(env_content)
    info(f"Created {env_path}")

    rptr_path = output_dir / "repeaters.json"
    rptr_path.write_text(repeaters_data)
    info(f"Created {rptr_path}")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def print_summary(config: dict, repeater_count: int, output_dir: str, dry_run: bool):
    """Print setup summary."""
    print()
    print("=" * 60)
    print(f"  {GREEN}{BOLD}NodusNet Edge Node — Setup Complete{NC}")
    print("=" * 60)
    print()

    print(f"  Node ID:       {BOLD}{config['node_id']}{NC}")
    print(f"  Metro:         {config['metro']} ({config['city']}, {config['state_abbrev']})")
    if config.get("callsign"):
        print(f"  Callsign:      {config['callsign']}")
    else:
        print(f"  Callsign:      (anonymous)")
    print()
    print(f"  Core freqs:    {len(config['core_frequencies'])} (always monitored)")
    print(f"  Candidate:     {len(config['candidate_frequencies'])} (promoted when active)")
    print(f"  Repeaters:     {repeater_count} saved")
    print()

    if not dry_run:
        print(f"  Files created:")
        print(f"    .env            -> {Path(output_dir) / '.env'}")
        print(f"    repeaters.json  -> {Path(output_dir) / 'repeaters.json'}")
        print()
        print(f"  Next steps:")
        print(f"    1. docker compose pull")
        print(f"    2. docker compose up -d")
        print(f"    3. Dashboard:  http://localhost:8073")

    print()
    print("=" * 60)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="NodusNet Edge Node Setup Wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  python setup-edge.py                    Interactive setup\n"
               "  python setup-edge.py --zip 85001        Start with Phoenix zip\n"
               "  python setup-edge.py --zip 85001 --callsign W1AW --non-interactive\n"
               "  python setup-edge.py --dry-run          Preview without writing files\n",
    )
    parser.add_argument("--zip", help="Zip code (skip prompt)")
    parser.add_argument("--lat", type=float, help="Latitude (skip zip lookup)")
    parser.add_argument("--lon", type=float, help="Longitude (skip zip lookup)")
    parser.add_argument("--city", help="City name")
    parser.add_argument("--state", help="State abbreviation (e.g. AZ)")
    parser.add_argument("--callsign", help="Operator callsign")
    parser.add_argument("--metro", help="Metro slug override")
    parser.add_argument("--server", help="NodusNet server URL (empty string = standalone)")
    parser.add_argument("--api-key", help="NodusNet API key")
    parser.add_argument("--sdr-device", type=int, help="RTL-SDR device index (default: 0)")
    parser.add_argument("--sdr-gain", help="RTL-SDR gain (0-49 or 'auto', default: 40)")
    parser.add_argument("--squelch", type=int, help="Squelch threshold override (default: 30)")
    parser.add_argument("--auto-squelch", action="store_true",
                        help="Auto-detect squelch by scanning noise floor (requires rtl_power)")
    parser.add_argument("--whisper-url", help="Whisper API URL")
    parser.add_argument("--output-dir", default=".", help="Output directory (default: current)")
    parser.add_argument("--radius", type=float, default=DEFAULT_RADIUS_MILES,
                        help=f"Repeater search radius in miles (default: {DEFAULT_RADIUS_MILES})")
    parser.add_argument("--non-interactive", action="store_true",
                        help="Skip all prompts, use defaults + args")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print config without writing files")
    return parser.parse_args()


def _auto_enroll_rem(server_url: str, node_id: str, callsign: str, metro: str):
    """Auto-enroll this node with REM. Warn but don't block on failure."""
    url = f"{server_url.rstrip('/')}/v1/edge/signup"
    payload = json.dumps({
        "callsign": callsign or "",
        "email": "",
        "metro": metro,
        "node_id": node_id,
    }).encode()

    try:
        req = Request(url, data=payload, method="POST")
        req.add_header("Content-Type", "application/json")
        req.add_header("User-Agent", USER_AGENT)
        with urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
        info(f"Enrolled with NodusNet ({data.get('node_id', node_id)})")
    except HTTPError as e:
        if e.code == 409:
            # Already enrolled, that's fine
            info(f"Node {node_id} already enrolled with NodusNet")
        else:
            warn(f"Could not enroll with NodusNet (HTTP {e.code}). Node will still work locally.")
    except Exception:
        warn("Could not reach NodusNet for enrollment. Node will still work locally.")


def main():
    args = parse_args()

    # Banner
    print()
    print("=" * 60)
    print(f"  {BOLD}NodusNet - Edge Node Setup{NC}")
    print("=" * 60)
    print()
    print("  This wizard guides you through the setup of a NodusEdge node")
    print("  (local capture of RF for the NodusNet ecosystem).")

    if args.dry_run:
        print()
        warn("DRY RUN MODE — no files will be written.")

    # Load CBSA zip->metro mapping
    zip_metro = load_zip_metro()
    if zip_metro:
        info(f"Loaded {len(zip_metro)} zip-to-metro mappings (CBSA)")
    else:
        warn("zip_metro.json not found — metro will be derived from city name.")
        info("Run: python scripts/generate-zip-metro.py to build it.")

    # Server connection (auto-configured, advanced users can edit .env)
    if args.non_interactive:
        server_config = ask_server_connection(args)
    else:
        server_url = "https://nodusrf.com"
        server_config = {
            "synapse_endpoint": server_url,
            "synapse_auth_token": "",
        }

    # Step 1: Location
    location = ask_location(args, zip_metro)

    # Step 2: Callsign
    callsign = ask_callsign(args)

    # Node ID (derived silently)
    node_id = derive_node_id(callsign, location["metro"])

    # Auto-enroll with REM
    if not args.non_interactive:
        _auto_enroll_rem(server_config["synapse_endpoint"], node_id, callsign, location["metro"])

    # Step 3: Repeater discovery
    core_hz, candidate_hz, repeaters, metadata = ask_repeaters(
        args, location["lat"], location["lon"], location["state"],
    )

    # Step 4: SDR device selection
    sdr_config = ask_sdr_device(args)

    # Step 5: RF environment (squelch)
    rf_config = ask_rf_environment(args, sdr_config)

    # Step 6: Whisper
    whisper_url = ask_whisper(args)

    # Build config
    config = {
        "node_id": node_id,
        "metro": location["metro"],
        "callsign": callsign,
        "city": location["city"],
        "state_abbrev": location.get("state_abbrev", ""),
        "core_frequencies": core_hz,
        "candidate_frequencies": candidate_hz,
        "whisper_api_url": whisper_url,
        "whisper_auth_token": server_config.get("synapse_auth_token", "") if "nodusrf.com" in (whisper_url or "") else "",
        "device_index": sdr_config["device_index"],
        "gain": sdr_config["gain"],
        **rf_config,
        **server_config,
    }

    # Step 7: Write output
    print()
    print(f"  {BOLD}Step 7: Generate Configuration{NC}")
    print(f"  {'─' * 50}")
    print()

    write_output(args, config, repeaters, metadata)

    # Summary
    print_summary(config, len(repeaters), args.output_dir, args.dry_run)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n  {YELLOW}Setup cancelled.{NC}\n")
        sys.exit(1)
