#!/usr/bin/env python3
"""
NodusNet FM Edge Node Setup Wizard

Interactive setup for FM (ham radio) edge nodes. Collects user inputs,
resolves geographic data, fetches local repeaters from RepeaterBook,
and generates .env + repeaters.json for Recept FM mode.

Usage:
    python setup-fm-edge.py                          # Interactive mode
    python setup-fm-edge.py --zip 85001 --non-interactive  # Scripted mode
    python setup-fm-edge.py --dry-run                # Preview without writing

Requires only Python 3.8+ stdlib (no pip install needed).
"""

import argparse
import hashlib
import json
import math
import os
import re
import socket
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ZIPPOPOTAM_API = "https://api.zippopotam.us/us/{zip}"
REPEATERBOOK_API = "https://www.repeaterbook.com/api/export.php"
USER_AGENT = "NodusNet-Setup/1.1 (https://nodusrf.com)"

# Path to bundled zip->metro CBSA mapping (generated by generate-zip-metro.py)
# Can be overridden via NODUSNET_ZIP_METRO_PATH env var
ZIP_METRO_PATH = Path(
    os.environ.get("NODUSNET_ZIP_METRO_PATH", "")
    or str(Path(__file__).resolve().parent / "data" / "zip_metro.json")
)

NATIONAL_SIMPLEX_2M_HZ = 146_520_000
DEFAULT_RADIUS_MILES = 50
CORE_FREQ_COUNT = 10

# Callsign regex: 1-2 letters, 1 digit, 1-3 letters (US format)
CALLSIGN_RE = re.compile(r"^[A-Za-z]{1,2}[0-9][A-Za-z]{1,3}$")
# Broader international format
CALLSIGN_BROAD_RE = re.compile(r"^[A-Za-z0-9]{3,7}$")

ZIP_RE = re.compile(r"^\d{5}$")

# Colors
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
BOLD = "\033[1m"
NC = "\033[0m"

# Complete US state FIPS codes (50 states + DC)
STATE_FIPS = {
    "Alabama": "01", "Alaska": "02", "Arizona": "04", "Arkansas": "05",
    "California": "06", "Colorado": "08", "Connecticut": "09", "Delaware": "10",
    "District of Columbia": "11", "Florida": "12", "Georgia": "13", "Hawaii": "15",
    "Idaho": "16", "Illinois": "17", "Indiana": "18", "Iowa": "19",
    "Kansas": "20", "Kentucky": "21", "Louisiana": "22", "Maine": "23",
    "Maryland": "24", "Massachusetts": "25", "Michigan": "26", "Minnesota": "27",
    "Mississippi": "28", "Missouri": "29", "Montana": "30", "Nebraska": "31",
    "Nevada": "32", "New Hampshire": "33", "New Jersey": "34", "New Mexico": "35",
    "New York": "36", "North Carolina": "37", "North Dakota": "38", "Ohio": "39",
    "Oklahoma": "40", "Oregon": "41", "Pennsylvania": "42", "Rhode Island": "44",
    "South Carolina": "45", "South Dakota": "46", "Tennessee": "47", "Texas": "48",
    "Utah": "49", "Vermont": "50", "Virginia": "51", "Washington": "53",
    "West Virginia": "54", "Wisconsin": "55", "Wyoming": "56",
}

STATE_ABBREV_TO_NAME = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
    "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine",
    "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska",
    "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico",
    "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
    "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island",
    "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas",
    "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
}

# State adjacency for border-metro repeater coverage
NEIGHBORING_STATES = {
    "Alabama": ["Florida", "Georgia", "Mississippi", "Tennessee"],
    "Alaska": [],
    "Arizona": ["California", "Colorado", "Nevada", "New Mexico", "Utah"],
    "Arkansas": ["Louisiana", "Mississippi", "Missouri", "Oklahoma", "Tennessee", "Texas"],
    "California": ["Arizona", "Nevada", "Oregon"],
    "Colorado": ["Arizona", "Kansas", "Nebraska", "New Mexico", "Oklahoma", "Utah", "Wyoming"],
    "Connecticut": ["Massachusetts", "New York", "Rhode Island"],
    "Delaware": ["Maryland", "New Jersey", "Pennsylvania"],
    "District of Columbia": ["Maryland", "Virginia"],
    "Florida": ["Alabama", "Georgia"],
    "Georgia": ["Alabama", "Florida", "North Carolina", "South Carolina", "Tennessee"],
    "Hawaii": [],
    "Idaho": ["Montana", "Nevada", "Oregon", "Utah", "Washington", "Wyoming"],
    "Illinois": ["Indiana", "Iowa", "Kentucky", "Missouri", "Wisconsin"],
    "Indiana": ["Illinois", "Kentucky", "Michigan", "Ohio"],
    "Iowa": ["Illinois", "Minnesota", "Missouri", "Nebraska", "South Dakota", "Wisconsin"],
    "Kansas": ["Colorado", "Missouri", "Nebraska", "Oklahoma"],
    "Kentucky": ["Illinois", "Indiana", "Missouri", "Ohio", "Tennessee", "Virginia", "West Virginia"],
    "Louisiana": ["Arkansas", "Mississippi", "Texas"],
    "Maine": ["New Hampshire"],
    "Maryland": ["Delaware", "District of Columbia", "Pennsylvania", "Virginia", "West Virginia"],
    "Massachusetts": ["Connecticut", "New Hampshire", "New York", "Rhode Island", "Vermont"],
    "Michigan": ["Indiana", "Ohio", "Wisconsin"],
    "Minnesota": ["Iowa", "North Dakota", "South Dakota", "Wisconsin"],
    "Mississippi": ["Alabama", "Arkansas", "Louisiana", "Tennessee"],
    "Missouri": ["Arkansas", "Illinois", "Iowa", "Kansas", "Kentucky", "Nebraska", "Oklahoma", "Tennessee"],
    "Montana": ["Idaho", "North Dakota", "South Dakota", "Wyoming"],
    "Nebraska": ["Colorado", "Iowa", "Kansas", "Missouri", "South Dakota", "Wyoming"],
    "Nevada": ["Arizona", "California", "Idaho", "Oregon", "Utah"],
    "New Hampshire": ["Maine", "Massachusetts", "Vermont"],
    "New Jersey": ["Delaware", "New York", "Pennsylvania"],
    "New Mexico": ["Arizona", "Colorado", "Oklahoma", "Texas", "Utah"],
    "New York": ["Connecticut", "Massachusetts", "New Jersey", "Pennsylvania", "Vermont"],
    "North Carolina": ["Georgia", "South Carolina", "Tennessee", "Virginia"],
    "North Dakota": ["Minnesota", "Montana", "South Dakota"],
    "Ohio": ["Indiana", "Kentucky", "Michigan", "Pennsylvania", "West Virginia"],
    "Oklahoma": ["Arkansas", "Colorado", "Kansas", "Missouri", "New Mexico", "Texas"],
    "Oregon": ["California", "Idaho", "Nevada", "Washington"],
    "Pennsylvania": ["Delaware", "Maryland", "New Jersey", "New York", "Ohio", "West Virginia"],
    "Rhode Island": ["Connecticut", "Massachusetts"],
    "South Carolina": ["Georgia", "North Carolina"],
    "South Dakota": ["Iowa", "Minnesota", "Montana", "Nebraska", "North Dakota", "Wyoming"],
    "Tennessee": ["Alabama", "Arkansas", "Georgia", "Kentucky", "Mississippi", "Missouri", "North Carolina", "Virginia"],
    "Texas": ["Arkansas", "Louisiana", "New Mexico", "Oklahoma"],
    "Utah": ["Arizona", "Colorado", "Idaho", "Nevada", "New Mexico", "Wyoming"],
    "Vermont": ["Massachusetts", "New Hampshire", "New York"],
    "Virginia": ["District of Columbia", "Kentucky", "Maryland", "North Carolina", "Tennessee", "West Virginia"],
    "Washington": ["Idaho", "Oregon"],
    "West Virginia": ["Kentucky", "Maryland", "Ohio", "Pennsylvania", "Virginia"],
    "Wisconsin": ["Illinois", "Iowa", "Michigan", "Minnesota"],
    "Wyoming": ["Colorado", "Idaho", "Montana", "Nebraska", "South Dakota", "Utah"],
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def info(msg: str) -> None:
    print(f"  {GREEN}[INFO]{NC} {msg}")


def warn(msg: str) -> None:
    print(f"  {YELLOW}[WARN]{NC} {msg}")


def error(msg: str) -> None:
    print(f"  {RED}[ERROR]{NC} {msg}")


def prompt(question: str, default: str = "", validator=None) -> str:
    """Prompt user for input with optional default and validation."""
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            answer = input(f"  {question}{suffix}: ").strip()
        except EOFError:
            answer = ""
        if not answer and default:
            answer = default
        if validator:
            err = validator(answer)
            if err:
                error(err)
                continue
        return answer


def prompt_yn(question: str, default_yes: bool = True) -> bool:
    """Prompt for yes/no answer."""
    hint = "Y/n" if default_yes else "y/N"
    while True:
        try:
            answer = input(f"  {question} [{hint}]: ").strip().lower()
        except EOFError:
            answer = ""
        if not answer:
            return default_yes
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        error("Please enter y or n.")


def load_zip_metro() -> dict:
    """Load the bundled zip->metro CBSA mapping if available."""
    if not ZIP_METRO_PATH.exists():
        return {}
    try:
        with open(ZIP_METRO_PATH) as f:
            data = json.load(f)
        return data.get("zips", {})
    except (json.JSONDecodeError, KeyError):
        return {}


def lookup_metro(zip_code: str, city: str, zip_metro: dict) -> str:
    """Resolve metro slug from zip code using CBSA mapping, with city fallback."""
    # Try CBSA mapping first (handles Elkhorn->omaha, Scottsdale->phoenix)
    if zip_code in zip_metro:
        return zip_metro[zip_code]
    # Fallback: slugify the city name from the zip API
    return slugify_city(city)


def slugify_city(city: str) -> str:
    """Normalize city name to a slug (fallback when CBSA mapping misses)."""
    slug = city.lower()
    slug = re.sub(r"[^a-z0-9]", "", slug)
    return slug[:20]


def haversine_distance(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Distance between two points in miles."""
    R = 3959  # Earth radius in miles
    lat1_r, lat2_r = math.radians(lat1), math.radians(lat2)
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_r) * math.cos(lat2_r) * math.sin(dlon / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ---------------------------------------------------------------------------
# Step 1: Server Connection
# ---------------------------------------------------------------------------

def ask_server_connection(args) -> dict:
    """Ask whether to connect to NodusNet server."""
    if args.non_interactive:
        server = args.server or ""
        token = args.api_key or ""
        return {
            "synapse_endpoint": f"{server}/v1/segments" if server else "",
            "synapse_auth_token": token,
        }

    print()
    print(f"  {BOLD}Step 1: Server Connection{NC}")
    print(f"  {'─' * 50}")
    print()

    connected = prompt_yn("Are you connecting to the NodusNet server?")

    if not connected:
        info("Standalone mode: segments will be saved locally only.")
        return {"synapse_endpoint": "", "synapse_auth_token": ""}

    server = prompt(
        "NodusNet server endpoint",
        default="https://nodusrf.com",
    )

    # Normalize: strip trailing slash
    server = server.rstrip("/")

    # Test connectivity
    try:
        req = Request(f"{server}/health")
        req.add_header("User-Agent", USER_AGENT)
        urlopen(req, timeout=5)
        info(f"Connected to {server}")
    except Exception:
        warn(f"Could not reach {server} — you can fix the endpoint in .env later.")

    token = ""
    has_key = prompt_yn("Do you have an API key?", default_yes=False)
    if has_key:
        token = prompt("API key")

    return {
        "synapse_endpoint": f"{server}/v1/segments",
        "synapse_auth_token": token,
    }


# ---------------------------------------------------------------------------
# Step 2: Location
# ---------------------------------------------------------------------------

def resolve_zip(zip_code: str) -> dict:
    """Resolve zip code via zippopotam.us API."""
    url = ZIPPOPOTAM_API.format(zip=zip_code)
    req = Request(url)
    req.add_header("User-Agent", USER_AGENT)

    with urlopen(req, timeout=10) as response:
        data = json.loads(response.read().decode("utf-8"))

    place = data["places"][0]
    return {
        "lat": float(place["latitude"]),
        "lon": float(place["longitude"]),
        "city": place["place name"],
        "state": place["state"],
        "state_abbrev": place["state abbreviation"],
    }


def ask_manual_location() -> dict:
    """Fall back to manual location entry."""
    print()
    warn("Enter your location manually:")

    def validate_float(v):
        try:
            float(v)
            return None
        except ValueError:
            return "Must be a number."

    def validate_state(v):
        if v.upper() not in STATE_ABBREV_TO_NAME:
            return "Unknown state abbreviation."
        return None

    lat = float(prompt("Latitude", validator=validate_float))
    lon = float(prompt("Longitude", validator=validate_float))
    city = prompt("City")
    state_abbrev = prompt("State abbreviation (e.g. AZ)", validator=validate_state).upper()
    state = STATE_ABBREV_TO_NAME[state_abbrev]

    return {
        "lat": lat,
        "lon": lon,
        "city": city,
        "state": state,
        "state_abbrev": state_abbrev,
    }


def ask_location(args, zip_metro: dict) -> dict:
    """Ask for zip code, resolve to location + metro."""
    if args.non_interactive:
        # Non-interactive: use CLI args
        if args.lat and args.lon and args.city and args.state:
            state_name = STATE_ABBREV_TO_NAME.get(args.state.upper(), args.state)
            loc = {
                "lat": args.lat, "lon": args.lon,
                "city": args.city, "state": state_name,
                "state_abbrev": args.state.upper(),
            }
            zip_code = args.zip or ""
        elif args.zip:
            loc = resolve_zip(args.zip)
            zip_code = args.zip
        else:
            error("Non-interactive mode requires --zip or --lat/--lon/--city/--state")
            sys.exit(1)

        metro = args.metro or lookup_metro(zip_code, loc["city"], zip_metro)
        loc["metro"] = metro
        return loc

    print()
    print(f"  {BOLD}Step 2: Location{NC}")
    print(f"  {'─' * 50}")
    print()

    zip_code = ""
    while True:
        zip_code = prompt("What is your zip code? (or 'manual' for manual entry)")

        if zip_code.lower() == "manual":
            loc = ask_manual_location()
            zip_code = ""
            break

        if not ZIP_RE.match(zip_code):
            error("Zip code must be exactly 5 digits.")
            continue

        try:
            loc = resolve_zip(zip_code)
            break
        except HTTPError as e:
            if e.code == 404:
                error(f"Zip code {zip_code} not found.")
            else:
                error(f"API error: {e.code}")
                if prompt_yn("Enter location manually?"):
                    loc = ask_manual_location()
                    zip_code = ""
                    break
        except (URLError, Exception) as e:
            warn(f"Could not reach zip code API: {e}")
            if prompt_yn("Enter location manually?"):
                loc = ask_manual_location()
                zip_code = ""
                break

    info(f"Location: {loc['city']}, {loc.get('state_abbrev', '')} ({loc['lat']:.4f}, {loc['lon']:.4f})")
    print()

    # Resolve metro via CBSA mapping, fall back to city name
    default_metro = lookup_metro(zip_code, loc["city"], zip_metro)
    cbsa_source = " (CBSA)" if zip_code in zip_metro else ""
    print(f"  Your metro area will be: {BOLD}{default_metro}{NC}{cbsa_source} ({loc['city']}, {loc.get('state_abbrev', '')})")
    choice = prompt("Is this correct? (y/n/custom metro name)", default="y")

    if choice.lower() in ("y", "yes", ""):
        loc["metro"] = default_metro
    elif choice.lower() in ("n", "no"):
        custom = prompt("Enter metro name")
        loc["metro"] = slugify_city(custom)
    else:
        # They typed a custom metro name directly
        loc["metro"] = slugify_city(choice)

    info(f"Metro: {loc['metro']}")
    return loc


# ---------------------------------------------------------------------------
# Step 3: Callsign
# ---------------------------------------------------------------------------

def ask_callsign(args) -> str:
    """Ask for operator callsign (optional)."""
    if args.non_interactive:
        return (args.callsign or "").upper()

    print()
    print(f"  {BOLD}Step 3: Callsign{NC}")
    print(f"  {'─' * 50}")
    print()

    callsign = prompt("What is your callsign? (optional, Enter to skip)")

    if not callsign:
        info("No callsign — node will be anonymous.")
        return ""

    callsign = callsign.upper()

    if CALLSIGN_RE.match(callsign):
        info(f"Callsign: {callsign}")
        return callsign

    if CALLSIGN_BROAD_RE.match(callsign):
        warn(f"{callsign} doesn't match standard US callsign format.")
        if prompt_yn("Use it anyway?"):
            return callsign
        return ""

    warn(f"{callsign} doesn't look like a valid callsign.")
    if prompt_yn("Use it anyway?", default_yes=False):
        return callsign
    return ""


# ---------------------------------------------------------------------------
# Step 4: Node ID
# ---------------------------------------------------------------------------

def derive_node_id(callsign: str, metro: str) -> str:
    """Derive node ID from callsign and metro."""
    if callsign:
        return f"{callsign.lower()}-fm-{metro}"
    else:
        seed = f"{socket.gethostname()}-{time.time()}"
        h = hashlib.sha256(seed.encode()).hexdigest()[:4]
        return f"anon-fm-{metro}-{h}"


# ---------------------------------------------------------------------------
# Step 5: Repeater Discovery
# ---------------------------------------------------------------------------

def get_states_to_query(state_name: str) -> list:
    """Return state + neighbors for RepeaterBook queries."""
    neighbors = NEIGHBORING_STATES.get(state_name, [])
    return [state_name] + neighbors


def fetch_state_repeaters(state_fips: str) -> list:
    """Fetch all repeaters for a state from RepeaterBook API."""
    url = f"{REPEATERBOOK_API}?state_id={state_fips}"
    req = Request(url)
    req.add_header("User-Agent", USER_AGENT)

    try:
        with urlopen(req, timeout=30) as response:
            data = json.loads(response.read().decode("utf-8"))
            return data.get("results", [])
    except HTTPError as e:
        if e.code == 429:
            warn(f"Rate limited, waiting 5s...")
            time.sleep(5)
            try:
                with urlopen(req, timeout=30) as response:
                    data = json.loads(response.read().decode("utf-8"))
                    return data.get("results", [])
            except Exception:
                return []
        return []
    except (URLError, json.JSONDecodeError):
        return []


def fetch_repeaters(lat: float, lon: float, state_name: str,
                    radius_miles: float = DEFAULT_RADIUS_MILES) -> tuple:
    """Fetch 2m repeaters near location from RepeaterBook.

    Returns (repeaters_list, metadata_dict).
    """
    states = get_states_to_query(state_name)
    all_repeaters = []
    metadata = {
        "center_lat": lat,
        "center_lon": lon,
        "radius_miles": radius_miles,
        "fetched_at": datetime.now(timezone.utc).isoformat(),
        "source": "RepeaterBook",
        "band": "2m",
        "states_queried": [],
    }

    print()
    info(f"Fetching 2m repeaters within {radius_miles} miles...")

    for state in states:
        fips = STATE_FIPS.get(state)
        if not fips:
            continue

        print(f"    Querying {state} (FIPS {fips})...", end=" ", flush=True)
        repeaters = fetch_state_repeaters(fips)

        # Filter by distance
        filtered = []
        for rptr in repeaters:
            try:
                rlat = float(rptr.get("Lat", 0))
                rlon = float(rptr.get("Long", 0))
                if rlat == 0 or rlon == 0:
                    continue
                dist = haversine_distance(lat, lon, rlat, rlon)
                if dist <= radius_miles:
                    rptr["_distance_miles"] = round(dist, 1)
                    filtered.append(rptr)
            except (ValueError, TypeError):
                continue

        # Filter to 2m band (144-148 MHz)
        filtered_2m = []
        for rptr in filtered:
            try:
                freq = float(rptr.get("Frequency", 0))
                if 144.0 <= freq <= 148.0:
                    filtered_2m.append(rptr)
            except (ValueError, TypeError):
                continue

        print(f"{len(repeaters)} total, {len(filtered_2m)} 2m within {radius_miles} mi")

        all_repeaters.extend(filtered_2m)
        metadata["states_queried"].append({
            "state": state,
            "fips": fips,
            "total": len(repeaters),
            "in_radius_2m": len(filtered_2m),
        })

        time.sleep(1)  # Rate limiting

    # Deduplicate by (Frequency, Callsign), sort by distance
    seen = set()
    unique = []
    for rptr in sorted(all_repeaters, key=lambda x: x.get("_distance_miles", 9999)):
        key = (rptr.get("Frequency"), rptr.get("Callsign"))
        if key not in seen:
            seen.add(key)
            unique.append(rptr)

    metadata["total_repeaters"] = len(unique)

    return unique, metadata


def split_frequencies(repeaters: list) -> tuple:
    """Split repeaters into core and candidate frequency lists.

    Returns (core_hz, candidate_hz).
    Core: national simplex + top 10 closest active repeaters.
    Candidate: remaining repeaters within radius.
    """
    core_hz = [NATIONAL_SIMPLEX_2M_HZ]

    # Filter to operational repeaters
    active = [r for r in repeaters
              if r.get("Operational Status", "").strip().lower() in ("on-air", "")]

    for rptr in active[:CORE_FREQ_COUNT]:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            if freq_hz not in core_hz:
                core_hz.append(freq_hz)
        except (ValueError, KeyError):
            continue

    core_set = set(core_hz)
    candidate_hz = []
    for rptr in active[CORE_FREQ_COUNT:]:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            if freq_hz not in core_set:
                candidate_hz.append(freq_hz)
        except (ValueError, KeyError):
            continue

    return core_hz, candidate_hz


def ask_repeaters(args, lat: float, lon: float, state_name: str) -> tuple:
    """Fetch repeaters and get user confirmation.

    Returns (core_hz, candidate_hz, repeaters, metadata).
    """
    radius = args.radius

    print()
    print(f"  {BOLD}Step 5: Repeater Discovery{NC}")
    print(f"  {'─' * 50}")

    repeaters, metadata = fetch_repeaters(lat, lon, state_name, radius)
    core_hz, candidate_hz = split_frequencies(repeaters)

    print()
    info(f"Found {len(repeaters)} repeaters in the 2m band within {radius} miles.")
    print()

    if core_hz:
        print(f"  {BOLD}Core frequencies (always monitored):{NC}")
        for freq_hz in core_hz:
            freq_mhz = freq_hz / 1_000_000
            # Find matching repeater info
            label = ""
            if freq_hz == NATIONAL_SIMPLEX_2M_HZ:
                label = "National simplex"
            else:
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                            cs = rptr.get("Callsign", "")
                            dist = rptr.get("_distance_miles", "?")
                            city = rptr.get("Nearest City", "")
                            label = f"{cs}  ({dist} mi) {city}"
                            break
                    except (ValueError, KeyError):
                        continue
            print(f"    {freq_mhz:>10.3f} MHz  {label}")

    if candidate_hz:
        print()
        print(f"  {BOLD}Candidate frequencies (promoted when active): {len(candidate_hz)}{NC}")
        # Show first 5 candidates
        for freq_hz in candidate_hz[:5]:
            freq_mhz = freq_hz / 1_000_000
            for rptr in repeaters:
                try:
                    if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                        cs = rptr.get("Callsign", "")
                        dist = rptr.get("_distance_miles", "?")
                        city = rptr.get("Nearest City", "")
                        print(f"    {freq_mhz:>10.3f} MHz  {cs}  ({dist} mi) {city}")
                        break
                except (ValueError, KeyError):
                    continue
        if len(candidate_hz) > 5:
            print(f"    ... and {len(candidate_hz) - 5} more")

    if not repeaters:
        warn("No 2m repeaters found in your area.")
        info("146.520 MHz (national simplex) will be your only core frequency.")
        info("You can add frequencies manually in the .env file later.")

    if not args.non_interactive:
        print()
        if not prompt_yn("Accept these frequencies?"):
            info("You can edit frequencies in the .env file after setup.")

    return core_hz, candidate_hz, repeaters, metadata


# ---------------------------------------------------------------------------
# Step 6: RTL-SDR Device Selection
# ---------------------------------------------------------------------------

def detect_rtlsdr_devices() -> list:
    """Detect RTL-SDR USB devices via lsusb."""
    import subprocess
    devices = []
    try:
        result = subprocess.run(
            ["lsusb"], capture_output=True, text=True, timeout=5,
        )
        for line in result.stdout.splitlines():
            # RTL2832U vendor:product IDs
            if "0bda:2838" in line or "0bda:2832" in line:
                devices.append(line.strip())
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return devices


def ask_sdr_device(args) -> dict:
    """Detect and select RTL-SDR device."""
    if args.non_interactive:
        return {
            "device_index": args.sdr_device if args.sdr_device is not None else 0,
            "gain": args.sdr_gain if args.sdr_gain is not None else 40,
        }

    print()
    print(f"  {BOLD}Step 6: RTL-SDR Device{NC}")
    print(f"  {'─' * 50}")
    print()

    devices = detect_rtlsdr_devices()

    if not devices:
        warn("No RTL-SDR devices detected via USB.")
        info("Make sure your dongle is plugged in before starting the containers.")
        info("Using default: device index 0, gain 40")
        return {"device_index": 0, "gain": 40}

    if len(devices) == 1:
        info(f"Found 1 RTL-SDR: {devices[0]}")
        device_index = 0
    else:
        info(f"Found {len(devices)} RTL-SDR devices:")
        for i, dev in enumerate(devices):
            print(f"    [{i}] {dev}")
        print()
        idx = prompt(f"Which device to use for FM scanning? (0-{len(devices)-1})", default="0")
        try:
            device_index = int(idx)
            if device_index < 0 or device_index >= len(devices):
                device_index = 0
                warn(f"Invalid index, using 0")
        except ValueError:
            device_index = 0

    gain = prompt("RTL-SDR gain (0-49, or 'auto')", default="40")

    return {
        "device_index": device_index,
        "gain": gain,
    }


# ---------------------------------------------------------------------------
# Step 7: RF Environment (Squelch)
# ---------------------------------------------------------------------------

RF_PRESETS = {
    "1": ("Urban / Noisy", "Near repeater sites, lots of RF", 40, 10.0),
    "2": ("Suburban / Moderate", "Default, good balance", 30, 6.0),
    "3": ("Rural / Quiet", "Weak signals, low noise floor", 20, 4.0),
}


def scan_noise_floor(device_index: int = 0, gain: str = "40") -> dict | None:
    """Scan 2m band with rtl_power to measure noise floor.

    Runs a quick sweep of 144-148 MHz and computes the 25th-percentile
    power level as the noise floor estimate.  Maps the result to
    recommended squelch / SNR settings.

    Returns dict with noise_floor_db, squelch_threshold,
    airband_squelch_snr_db, and label — or None on failure.
    """
    import shutil
    import subprocess
    import tempfile

    if not shutil.which("rtl_power"):
        return None

    fd, csv_path = tempfile.mkstemp(suffix=".csv")
    os.close(fd)

    try:
        cmd = [
            "rtl_power",
            "-d", str(device_index),
            "-f", "144M:148M:25k",  # 2m band, 25 kHz bins
            "-i", "2",               # 2s integration per window
            "-1",                     # single sweep then exit
        ]
        if gain and str(gain).lower() != "auto":
            cmd.extend(["-g", str(gain)])
        cmd.append(csv_path)

        subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        # Parse CSV: date, time, Hz_low, Hz_high, Hz_step, samples, dB, dB, ...
        powers = []
        with open(csv_path) as f:
            for line in f:
                parts = line.strip().split(",")
                if len(parts) > 6:
                    for val in parts[6:]:
                        try:
                            powers.append(float(val.strip()))
                        except ValueError:
                            pass

        if not powers:
            return None

        return classify_noise_floor(powers)
    except (subprocess.TimeoutExpired, OSError):
        return None
    finally:
        try:
            os.unlink(csv_path)
        except OSError:
            pass


def classify_noise_floor(powers: list) -> dict:
    """Map a list of power readings (dB) to squelch recommendations.

    Uses the 25th percentile as the noise floor estimate to avoid
    active signals skewing the result upward.
    """
    powers_sorted = sorted(powers)
    idx_25 = max(0, len(powers_sorted) // 4)
    noise_floor = powers_sorted[idx_25]

    if noise_floor > -45:
        sq, snr, label = 45, 12.0, "Very noisy"
    elif noise_floor > -55:
        sq, snr, label = 40, 10.0, "Urban / Noisy"
    elif noise_floor > -65:
        sq, snr, label = 30, 6.0, "Suburban / Moderate"
    else:
        sq, snr, label = 20, 4.0, "Rural / Quiet"

    return {
        "noise_floor_db": round(noise_floor, 1),
        "squelch_threshold": sq,
        "airband_squelch_snr_db": snr,
        "label": label,
    }


def ask_rf_environment(args, sdr_config: dict | None = None) -> dict:
    """Ask about RF environment to set squelch thresholds."""
    # CLI override takes priority
    if args.squelch is not None:
        return {
            "squelch_threshold": args.squelch,
            "airband_squelch_snr_db": 6.0,
        }

    if args.non_interactive:
        if getattr(args, "auto_squelch", False):
            device_index = (sdr_config or {}).get("device_index", 0)
            gain = (sdr_config or {}).get("gain", 40)
            result = scan_noise_floor(device_index, str(gain))
            if result:
                return {
                    "squelch_threshold": result["squelch_threshold"],
                    "airband_squelch_snr_db": result["airband_squelch_snr_db"],
                }
        return {"squelch_threshold": 30, "airband_squelch_snr_db": 6.0}

    print()
    print(f"  {BOLD}Step 7: RF Environment{NC}")
    print(f"  {'─' * 50}")
    print()
    print("  Squelch controls how much signal is needed to start recording.")
    print("  Too low = static-only recordings. Too high = missed weak signals.")
    print()

    for key, (name, desc, sq, snr) in RF_PRESETS.items():
        print(f"    [{key}] {BOLD}{name}{NC}")
        print(f"        {desc} (squelch {sq}, SNR {snr} dB)")

    # Only show auto-detect if rtl_power is available
    import shutil
    has_rtl_power = shutil.which("rtl_power") is not None
    if has_rtl_power:
        print(f"    [A] {BOLD}Auto-detect{NC}")
        print(f"        Scan 2m band with RTL-SDR to measure noise floor (~10s)")
    print()

    default = "A" if has_rtl_power else "2"
    choice = prompt("Select RF environment", default=default)

    if choice.upper() == "A" and has_rtl_power:
        device_index = (sdr_config or {}).get("device_index", 0)
        gain = (sdr_config or {}).get("gain", 40)
        info("Scanning 2m band for noise floor — this takes about 10 seconds...")
        result = scan_noise_floor(device_index, str(gain))
        if result:
            info(f"Noise floor: {result['noise_floor_db']:.1f} dB → {result['label']}")
            info(f"Recommended squelch: {result['squelch_threshold']}, SNR: {result['airband_squelch_snr_db']} dB")
            print()
            if prompt_yn("Accept these settings?"):
                return {
                    "squelch_threshold": result["squelch_threshold"],
                    "airband_squelch_snr_db": result["airband_squelch_snr_db"],
                }
            warn("Falling back to manual selection.")
            choice = prompt("Select preset (1/2/3)", default="2")
        else:
            warn("Scan failed — RTL-SDR may be unavailable or busy.")
            warn("Falling back to manual selection.")
            choice = prompt("Select preset (1/2/3)", default="2")

    if choice not in RF_PRESETS:
        warn(f"Unknown choice '{choice}', using Suburban / Moderate.")
        choice = "2"

    _, _, squelch, snr = RF_PRESETS[choice]
    info(f"Squelch threshold: {squelch}, SNR: {snr} dB")
    print(f"  Tip: raise squelch if you get static-only recordings, lower if missing weak signals.")

    return {"squelch_threshold": squelch, "airband_squelch_snr_db": snr}


# ---------------------------------------------------------------------------
# Step 8: Transcription (Whisper)
# ---------------------------------------------------------------------------

def ask_whisper(args) -> str:
    """Ask for Whisper transcription endpoint."""
    if args.non_interactive:
        # Default to Docker internal DNS when not explicitly set
        return args.whisper_url if args.whisper_url is not None else "http://whisper:8000"

    print()
    print(f"  {BOLD}Step 8: Transcription{NC}")
    print(f"  {'─' * 50}")
    print()

    default_url = args.whisper_url if args.whisper_url is not None else "http://whisper:8000"
    url = prompt(
        "Whisper transcription endpoint",
        default=default_url,
    )

    if url:
        # Skip connectivity test for Docker internal DNS (container isn't running yet)
        if "://whisper:" in url:
            info(f"Using Docker internal DNS: {url}")
        else:
            # Test connectivity
            try:
                req = Request(url)
                req.add_header("User-Agent", USER_AGENT)
                urlopen(req, timeout=5)
                info(f"Whisper reachable at {url}")
            except Exception:
                warn(f"Could not reach {url} — you can fix this in .env later.")
    else:
        info("Transcription disabled. Set RECEPT_WHISPER_API_URL in .env to enable.")

    return url


# ---------------------------------------------------------------------------
# Step 9: Generate Output
# ---------------------------------------------------------------------------

ENV_TEMPLATE = """\
# NodusNet FM Edge Node Configuration
# Generated by setup-fm-edge.py on {generated_at}
# Node: {node_id} | Metro: {metro}

# ---- Identity ----
RECEPT_MODE=fm
RECEPT_NODE_ID={node_id}
RECEPT_METRO={metro}
RECEPT_CALLSIGN={callsign}

# ---- Scanner ----
RECEPT_FM_SCANNER_BACKEND=airband
RECEPT_FM_CORE_FREQUENCIES={core_frequencies}
RECEPT_FM_CANDIDATE_FREQUENCIES={candidate_frequencies}
RECEPT_FM_RTL_DEVICE_INDEX={device_index}
RECEPT_FM_GAIN={gain}
# Squelch: raise if you get static-only recordings, lower if missing weak signals
RECEPT_FM_SQUELCH_THRESHOLD={squelch_threshold}
RECEPT_FM_AIRBAND_SQUELCH_SNR_DB={airband_squelch_snr_db}

# ---- Upstream ----
RECEPT_SYNAPSE_ENDPOINT={synapse_endpoint}
RECEPT_SYNAPSE_AUTH_TOKEN={synapse_auth_token}
RECEPT_DIAGNOSTICS_ENDPOINT={diagnostics_endpoint}

# ---- Transcription ----
RECEPT_WHISPER_API_URL={whisper_api_url}
RECEPT_TRANSCRIPTION_ENABLED={transcription_enabled}
WHISPER_MODEL={whisper_model}

# ---- Paths ----
RECEPT_FM_CAPTURE_DIR=./fm_capture
RECEPT_OUTPUT_DIR=./output

# ---- Logging ----
RECEPT_LOG_LEVEL=INFO
"""


def generate_env(output_dir: Path, config: dict) -> str:
    """Generate .env file content."""
    # Diagnostics endpoint defaults to same base as Synapse
    synapse_ep = config.get("synapse_endpoint", "")
    diagnostics_ep = config.get("diagnostics_endpoint", "") or synapse_ep

    return ENV_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).isoformat(),
        node_id=config["node_id"],
        metro=config["metro"],
        callsign=config.get("callsign", ""),
        core_frequencies=json.dumps(config["core_frequencies"]),
        candidate_frequencies=json.dumps(config["candidate_frequencies"]),
        synapse_endpoint=synapse_ep,
        synapse_auth_token=config.get("synapse_auth_token", ""),
        diagnostics_endpoint=diagnostics_ep,
        whisper_api_url=config.get("whisper_api_url", ""),
        transcription_enabled="true" if config.get("whisper_api_url") else "false",
        whisper_model=config.get("whisper_model", "base"),
        device_index=config.get("device_index", 0),
        gain=config.get("gain", 40),
        squelch_threshold=config.get("squelch_threshold", 30),
        airband_squelch_snr_db=config.get("airband_squelch_snr_db", 6.0),
    )


def write_output(args, config: dict, repeaters: list, metadata: dict):
    """Write .env and repeaters.json to output directory."""
    output_dir = Path(args.output_dir)

    env_content = generate_env(output_dir, config)
    repeaters_data = json.dumps({"metadata": metadata, "repeaters": repeaters}, indent=2)

    if args.dry_run:
        print()
        print(f"  {BOLD}[DRY-RUN] .env contents:{NC}")
        for line in env_content.splitlines():
            print(f"    {line}")
        print()
        print(f"  {BOLD}[DRY-RUN] repeaters.json:{NC} {len(repeaters)} repeaters")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    env_path = output_dir / ".env"
    env_path.write_text(env_content)
    info(f"Created {env_path}")

    rptr_path = output_dir / "repeaters.json"
    rptr_path.write_text(repeaters_data)
    info(f"Created {rptr_path}")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def print_summary(config: dict, repeater_count: int, output_dir: str, dry_run: bool):
    """Print setup summary."""
    print()
    print("=" * 60)
    print(f"  {GREEN}{BOLD}NodusNet FM Edge Node — Setup Complete{NC}")
    print("=" * 60)
    print()

    mode = "NodusNet (remote Synapse)" if config.get("synapse_endpoint") else "Standalone (local only)"

    print(f"  Node ID:       {BOLD}{config['node_id']}{NC}")
    print(f"  Metro:         {config['metro']} ({config['city']}, {config['state_abbrev']})")
    if config.get("callsign"):
        print(f"  Callsign:      {config['callsign']}")
    else:
        print(f"  Callsign:      (anonymous)")
    print(f"  Mode:          {mode}")
    print()
    print(f"  Core freqs:    {len(config['core_frequencies'])} (always monitored)")
    print(f"  Candidate:     {len(config['candidate_frequencies'])} (promoted when active)")
    print(f"  Repeaters:     {repeater_count} saved")
    print()

    if not dry_run:
        print(f"  Files created:")
        print(f"    .env            -> {Path(output_dir) / '.env'}")
        print(f"    repeaters.json  -> {Path(output_dir) / 'repeaters.json'}")
        print()
        print(f"  Next steps:")
        print(f"    1. docker compose pull")
        print(f"    2. docker compose up -d")
        print(f"    3. Dashboard:  http://localhost:8073")

    print()
    print("=" * 60)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="NodusNet FM Edge Node Setup Wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  python setup-fm-edge.py                    Interactive setup\n"
               "  python setup-fm-edge.py --zip 85001        Start with Phoenix zip\n"
               "  python setup-fm-edge.py --zip 85001 --callsign W1AW --non-interactive\n"
               "  python setup-fm-edge.py --dry-run          Preview without writing files\n",
    )
    parser.add_argument("--zip", help="Zip code (skip prompt)")
    parser.add_argument("--lat", type=float, help="Latitude (skip zip lookup)")
    parser.add_argument("--lon", type=float, help="Longitude (skip zip lookup)")
    parser.add_argument("--city", help="City name")
    parser.add_argument("--state", help="State abbreviation (e.g. AZ)")
    parser.add_argument("--callsign", help="Operator callsign")
    parser.add_argument("--metro", help="Metro slug override")
    parser.add_argument("--server", help="NodusNet server URL (empty string = standalone)")
    parser.add_argument("--api-key", help="NodusNet API key")
    parser.add_argument("--sdr-device", type=int, help="RTL-SDR device index (default: 0)")
    parser.add_argument("--sdr-gain", help="RTL-SDR gain (0-49 or 'auto', default: 40)")
    parser.add_argument("--squelch", type=int, help="Squelch threshold override (default: 30)")
    parser.add_argument("--auto-squelch", action="store_true",
                        help="Auto-detect squelch by scanning noise floor (requires rtl_power)")
    parser.add_argument("--whisper-url", help="Whisper API URL")
    parser.add_argument("--output-dir", default=".", help="Output directory (default: current)")
    parser.add_argument("--radius", type=float, default=DEFAULT_RADIUS_MILES,
                        help=f"Repeater search radius in miles (default: {DEFAULT_RADIUS_MILES})")
    parser.add_argument("--non-interactive", action="store_true",
                        help="Skip all prompts, use defaults + args")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print config without writing files")
    return parser.parse_args()


def main():
    args = parse_args()

    # Banner
    print()
    print("=" * 60)
    print(f"  {BOLD}NodusNet FM Edge Node Setup{NC}")
    print("=" * 60)
    print()
    print("  This wizard configures a new FM (ham radio) edge node")
    print("  for NodusNet. It will generate .env and repeaters.json.")

    if args.dry_run:
        print()
        warn("DRY RUN MODE — no files will be written.")

    # Load CBSA zip->metro mapping
    zip_metro = load_zip_metro()
    if zip_metro:
        info(f"Loaded {len(zip_metro)} zip-to-metro mappings (CBSA)")
    else:
        warn("zip_metro.json not found — metro will be derived from city name.")
        info("Run: python scripts/generate-zip-metro.py to build it.")

    # Step 1: Server connection
    server_config = ask_server_connection(args)

    # Step 2: Location
    location = ask_location(args, zip_metro)

    # Step 3: Callsign
    callsign = ask_callsign(args)

    # Step 4: Node ID
    node_id = derive_node_id(callsign, location["metro"])
    print()
    print(f"  {BOLD}Step 4: Node Identity{NC}")
    print(f"  {'─' * 50}")
    print()
    info(f"Your node ID: {BOLD}{node_id}{NC}")

    # Step 5: Repeater discovery
    core_hz, candidate_hz, repeaters, metadata = ask_repeaters(
        args, location["lat"], location["lon"], location["state"],
    )

    # Step 6: SDR device selection
    sdr_config = ask_sdr_device(args)

    # Step 7: RF environment (squelch)
    rf_config = ask_rf_environment(args, sdr_config)

    # Step 8: Whisper
    whisper_url = ask_whisper(args)

    # Build config
    config = {
        "node_id": node_id,
        "metro": location["metro"],
        "callsign": callsign,
        "city": location["city"],
        "state_abbrev": location.get("state_abbrev", ""),
        "core_frequencies": core_hz,
        "candidate_frequencies": candidate_hz,
        "whisper_api_url": whisper_url,
        "device_index": sdr_config["device_index"],
        "gain": sdr_config["gain"],
        **rf_config,
        **server_config,
    }

    # Step 9: Write output
    print()
    print(f"  {BOLD}Step 9: Generate Configuration{NC}")
    print(f"  {'─' * 50}")
    print()

    write_output(args, config, repeaters, metadata)

    # Summary
    print_summary(config, len(repeaters), args.output_dir, args.dry_run)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n  {YELLOW}Setup cancelled.{NC}\n")
        sys.exit(1)
